import React,{useEffect,useRef,useState} from 'react';
import {getChannels,submitVideo,getMyUploads,login,API_BASE} from './api';
import {Icon,Brand,LegalLinks,Empty,Notice,Stat,LoginArt} from './ui';

const GENRES=['Comedy','Motivation','Food','Tech','Lifestyle','Other'];
const STATUS={pending:'In review',approved:'Approved',rejected:'Rejected',published:'Published',processing:'Processing',publishing:'Publishing',publish_unknown:'Under review'};

function Dashboard(){
  const [channels,setChannels]=useState([]),[mine,setMine]=useState([]),[loading,setLoading]=useState(true),[channelLoading,setChannelLoading]=useState(true),[message,setMessage]=useState(null),[submitting,setSubmitting]=useState(false),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[drag,setDrag]=useState(false);
  const [section,setSection]=useState('submit');
  const [form,setForm]=useState({genre:GENRES[0],channel_id:'',title:'',description:''});
  const name=sessionStorage.getItem('team_name')||'Team member';
  const fileInput=useRef(null), formRef=useRef(null);
  async function refresh(){try{setMine(await getMyUploads());}catch(e){setMessage({text:e.message});}finally{setLoading(false);}}
  useEffect(()=>{let active=true;getChannels().then(data=>{if(active)setChannels(data);}).catch(e=>{if(active)setMessage({text:e.message});}).finally(()=>{if(active)setChannelLoading(false);});refresh();return()=>{active=false;};},[]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  function chooseFile(selected){if(!selected)return;if(selected.size>50*1024*1024 || !selected.name.toLowerCase().endsWith('.mp4')){setMessage({text:'Choose an MP4 video up to 50 MB.'});setFile(null);if(fileInput.current)fileInput.current.value='';return;}setFile(selected);setMessage(null);}
  async function handleSubmit(e){e.preventDefault();if(!file||!form.channel_id||!form.title.trim()){setMessage({text:'Add your video, a title, and a destination channel.'});return;}setSubmitting(true);setMessage(null);try{const data=new FormData();for(const [k,v]of Object.entries(form))data.append(k,v);data.append('file',file);await submitVideo(data);setMessage({type:'success',text:'Your story is in! It’s now waiting for your admin’s review.'});setForm({...form,title:'',description:''});setFile(null);if(fileInput.current)fileInput.current.value='';await refresh();}catch(e){setMessage({text:e.message});}finally{setSubmitting(false);}}
  const initials=name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase();
  return <div className="workspace"><aside className="sidebar"><Brand/><div className="sidebar-label">CREATOR WORKSPACE</div><nav className="side-nav" aria-label="Main navigation"><a href="#submit" className={section==='submit'?'active':''} onClick={()=>setSection('submit')}><Icon name="upload"/>New submission<Icon name="arrow" size={13} className="nav-arrow"/></a><a href="#history" className={section==='history'?'active':''} onClick={()=>{setSection('history');refresh();}}><Icon name="film"/>My submissions</a></nav><div className="sidebar-note"><Icon name="spark"/><strong>Every story starts with you.</strong>Create it. Give it a voice. We'll take care of the next step together.</div><div className="sidebar-account"><span className="avatar">{initials}</span><div><strong>{name}</strong><small>Creative team</small></div><button aria-label="Log out" title="Log out" onClick={()=>{sessionStorage.removeItem('team_token');sessionStorage.removeItem('team_name');location.reload();}}><Icon name="logout" size={16}/></button></div></aside>
    <header className="topbar"><div className="breadcrumb">Workspace<span>/</span><strong>{section==='history'?'My submissions':'New submission'}</strong></div><span className="workspace-label"><span className="dot"/>Creator workspace</span></header><main className="layout"><div className="page-heading"><div><span className="eyebrow">FROM YOUR IMAGINATION TO THE WORLD</span><h1>Let’s give your story a home.</h1><p className="lede">Upload your finished cut. Your team will take it from here.</p></div><span className="badge status-approved"><Icon name="spark" size={12}/>Hello, {name.split(' ')[0]}</span></div>
    <div className="stats-grid"><Stat label="Your submissions" icon="film" value={loading?'—':mine.length} note="Stories in this workspace"/><Stat label="In review" icon="clock" value={loading?'—':mine.filter(v=>v.status==='pending').length} note="Getting a second pair of eyes"/><Stat label="Approved" icon="check" value={loading?'—':mine.filter(v=>v.status==='approved').length} note="Ready for the next step"/><Stat label="Published" icon="play" value={loading?'—':mine.filter(v=>v.status==='published').length} note="Your stories, shared"/></div>
    <Notice message={message}/><div className="creator-layout"><section className="panel" id="submit"><div className="panel-head"><div className="section-title"><span className="section-number">01</span><div><h2>A new story</h2><p>The final cut, with all the finishing touches.</p></div></div><Icon name="film" size={20}/></div>
      <form className="form" ref={formRef} onSubmit={handleSubmit}><label className={`upload-zone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!submitting)chooseFile(e.dataTransfer.files[0]);}}><span className="upload-icon"><Icon name={file?'check':'upload'} size={22}/></span><strong>{file?file.name:'Drop your finished video here'}</strong><small>{file?`${(file.size/1024/1024).toFixed(1)} MB · Click to choose another file`:'or click to browse · MP4 · Up to 50 MB'}</small><input ref={fileInput} type="file" aria-label="Upload MP4 video" accept="video/mp4,.mp4" disabled={submitting} onChange={e=>chooseFile(e.target.files[0])}/></label>
      {preview&&<video className="file-preview" src={preview} controls aria-label="Your selected video preview"/>}
      <label className="field">Story title<input value={form.title} maxLength={100} placeholder="Give your story a memorable title" required disabled={submitting} onChange={e=>setForm({...form,title:e.target.value})}/></label>
      <div className="field-row"><label className="field">Content genre<select value={form.genre} disabled={submitting} onChange={e=>setForm({...form,genre:e.target.value})}>{GENRES.map(g=><option key={g}>{g}</option>)}</select></label><label className="field">Destination channel<select value={form.channel_id} required disabled={submitting||channelLoading} onChange={e=>setForm({...form,channel_id:e.target.value})}><option value="" disabled>{channelLoading?'Loading channels…':'Choose a channel'}</option>{channels.map(c=><option key={c.id} value={c.id}>{c.display_name} ({c.platform==='youtube'?'YouTube':'Instagram'})</option>)}</select></label></div>
      {!channelLoading&&!channels.length&&<p className="field-hint">Your admin needs to connect a channel before you can submit.</p>}
      <label className="field"><span>Description <span className="optional">(optional)</span></span><textarea rows={3} value={form.description} maxLength={2200} placeholder="A little context, your credits, or a few hashtags…" disabled={submitting} onChange={e=>setForm({...form,description:e.target.value})}/></label>
      <div className="submit-bottom"><p>Submitting as <strong>{name}</strong>.<br/>Nothing is published without review.</p><button className="primary" disabled={submitting||!channels.length}>{submitting?<span className="spinner"/>:<Icon name="arrow"/>}{submitting?'Sending your story…':'Send for review'}</button></div></form>
    </section><aside className="right-column"><section className="panel" id="history"><div className="panel-head"><div><h2>Your submissions</h2><p>A little progress, one story at a time.</p></div><button className="text-button" aria-label="Refresh submissions" title="Refresh submissions" onClick={refresh}><Icon name="refresh" size={16}/></button></div>{loading?<div className="loading">Loading your stories…</div>:!mine.length?<Empty title="Your first story belongs here">Once you submit a video, you can follow its progress right here.</Empty>:<ul className="list">{mine.map(v=><li className="list-row" key={v.id}><span className="list-icon"><Icon name="play" size={16}/></span><div className="list-content"><div className="list-title">{v.title}</div><div className="list-meta">{v.genre} · #{v.id}</div></div><span className={`status status-${v.status}`}>{STATUS[v.status]||v.status}</span></li>)}</ul>}</section>
    <section className="guide-card"><h3><Icon name="spark" size={17}/>From idea to published.</h3><ol><li><b>1</b><div><strong>Bring your story to life</strong><p>AI images, a thoughtful edit, and your voice. Aim for a 40–55 second finished cut.</p></div></li><li><b>2</b><div><strong>Send it for a second look</strong><p>Pick the right channel and upload your finished MP4, up to 50 MB.</p></div></li><li><b>3</b><div><strong>Let your admin take it from here</strong><p>They’ll review it, approve it, and publish to the selected channel.</p></div></li></ol></section></aside></div></main><LegalLinks base={API_BASE}/></div>;
}

export default function App(){
  const [signedIn,setSignedIn]=useState(Boolean(sessionStorage.getItem('team_token'))),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  if(signedIn)return <Dashboard/>;
  return <div className="login-page"><LoginArt/><main className="login-main"><div className="login-box"><span className="eyebrow">CREATOR WORKSPACE</span><h2>Good to see you.</h2><p className="lede">A new idea. A finished cut. A story to share.<br/>Let’s get it out there.</p><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await login(username,password);setSignedIn(true);}catch(e){setError(e.message);}finally{setBusy(false);}}}><label className="field">Username<input autoComplete="username" placeholder="Enter your username" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="field">Password<input type="password" autoComplete="current-password" placeholder="Enter your password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><Notice message={error?{text:error}:null}/><button className="primary" disabled={busy}>{busy?<span className="spinner"/>:null}{busy?'Signing in…':'Sign in to your workspace'}<Icon name="arrow"/></button></form><div className="login-lock"><Icon name="lock" size={12}/>Your administrator provides your account.</div></div><LegalLinks base={API_BASE}/></main></div>;
}
